### ISSUE TITLE
[Feat] 텍스트 필드 리턴 키 눌렀을 때 다음 텍스트 필드로 포커싱 이동 #6

### ISSUE THREAD

**Issue by Gnoam-R** [iOS-YouTube-CloneCoding/Youtube_Clone_Gnoam#6]
## 📌  Feature Issue
- 텍스트 필드 리턴 키 눌렀을 때 다음 텍스트 필드로 포커싱 이동 

<br>
<h1 align="center">
<img src="https://github.com/iOS-YouTube-CloneCoding/Youtube_Clone_Gnoam/assets/67363759/de6c375b-4f04-4b87-8916-09f02563b0e9" width="250" height="550"/>

<br>
<br>
아래의 subView들이 가려지는 이슈가 있음
<br><br>

## 📝  To-do
- [x] 키보드 리스너 함수 구현
- [x] Done Event 처리
- [ ] 키보드 height로 아래 subView가 가려지지 않고 전체적인 view의 vertical layout이 변경되도록 수정
